[package]
name = "client"
version = "0.1.0"
authors = ["shiki <shiki.tak@gmail.com>"]
edition = "2018"

[dependencies]
redis = "0.10.0"
# TODO: create util mod
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

model = { package = "model", path = "../model/" }