[package]
name = "merkle"
version = "0.1.0"
authors = ["shiki <shiki.tak@gmail.com>"]
edition = "2018"

[dependencies]
ethereum-rust-utils = ""

transaction = { package = "transaction", path = "../transaction/" }