[package]
name = "plasma-mvp-rust"
version = "0.1.0"
authors = ["shiki <shiki.tak@gmail.com>"]
edition = "2018"

[dependencies]
block = { package = "block", path = "./plasma_core/block" }
transaction = { package = "transaction", path = "./plasma_core/transaction/" }